Commiting day3 tasks
Nandakumar-Nandhi/HomeTask-02 pull request #3
Opened 2023-02-14 05:47 UTC by Nandakumar-Nandhi

Please review Day3 tasks

2023-02-22 05:00 UTC, NirmalaEpam requested changes

2023-02-22 05:00 UTC, NirmalaEpam commented on Daily Tasks- Day 3/Question3.js
> +function createFunctions(n) {
![image](https://user-images.githubusercontent.com/98024910/220526008-13c7d960-332d-4886-b785-20fb16c9aad4.png)
 This function is not working as required . Do check again on the logic

2023-02-22 05:00 UTC, NirmalaEpam commented on Daily Tasks- Day 3/Question3.js
> +function createFunctions(n) {
Everytime it returns 5 rather than the index value

2023-02-22 05:03 UTC, Nandakumar-Nandhi commented on Daily Tasks- Day 3/Question3.js
> +function createFunctions(n) {
Sorry its actually the problem with var, it works if we declare i with let, I will change it now.

2023-03-15 12:26 UTC, NirmalaEpam approved these changes

2023-03-15 12:27 UTC, merged